apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-health-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-health
  template:
    metadata:
      labels:
        app: go-health
    spec:
      containers:
      - name: go-health-container
        image: innoskrit/go-k8s-deployment
        ports:
        - containerPort: 8085
