apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-health-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-health
  template:
    metadata:
      labels:
        app: go-health
    spec:
      containers:
      - name: go-health-container
        image: innoskrit/go-k8s-deployment
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: go-health-service
spec:
  selector:
    app: go-health-app
  ports:
    - protocol: TCP
      port: 85
      targetPort: 8085
  type: NodePort
